apps/app2_manage_users/urls.py
#app-level url code:
from django.conf.urls import url, include
from . import views

# APP2
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_user$', views.add_user, name='add_user'),
    url(r'^edit_user/(?P<id>\d+)$', views.edit_user, name='edit_user'),
    url(r'^edit_password/(?P<id>\d+)$', views.edit_password, name='edit_password'),
    url(r'^remove_user_check/(?P<id>\d+)$', views.deletecheck, name='check'),
    # url(r'^remove_user$', views.remove_user, name='remove')
    url(r'^remove_user/(?P<id>\d+)$', views.remove_user, name='remove_user')
]

apps/app3_messages/urls.py
#app-level url code:
from django.conf.urls import url, include
from . import views

# app3_messages
urlpatterns = [
# route for rendering all_users.html:
    url(r'^$', views.all_users, name='all_users'),

# route for rendering edit_profile.html:
    url(r'^edit_profile/(?P<id>\d+)$', views.edit_profile, name='edit_profile'),

# route for sending form data in edit info box on edit_profile.html:
    url(r'^edit_info/(?P<id>\d+)$', views.edit_info, name='edit_info'),

# route for sending form data in change password box on edit_profile.html:
    url(r'^change_pw/(?P<id>\d+)$', views.change_pw, name='change_pw'),

# route for sending form data in edit description box on edit_profile.html:
    url(r'^edit_desc/(?P<id>\d+)$', views.edit_desc, name='edit_desc'),


    url(r'^profile/(?P<id>\d+)$', views.profile, name='profile'),


    url(r'^user_posts/(?P<id>\d+)$', views.user_posts, name='user_posts'),

    # url(r'^user_update$', views.user_update, name='user_update'),
    # url(r'^display_messages/(?P<id>\d+)$', views.display_messages, name='display'),
]

user_dashboard2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.app1_login_register.urls', namespace="loginreg")),
    url(r'^admins/', include('apps.app2_manage_users.urls', namespace='admins')),
    url(r'^messages/', include('apps.app3_messages.urls', namespace='messages')),
]

apps/app3_messages/models.py
from django.db import models
from apps.app1_login_register.models import User

# Create your models here.
class User_profile(models.Model):
    user_id=models.OneToOneField(User)
    description=models.CharField(max_length=255)

class User_posts(models.Model):
    post = models.CharField(max_length=255)
    user_posts= models.ManyToManyField(User, related_name = "posts")
    created_at = models.DateTimeField(auto_now_add=True)

    

apps/app3_messages/views.py
from django.shortcuts import render, HttpResponse, redirect
from apps.app1_login_register.models import User
from .models import *
from django.contrib import messages
import re, bcrypt
# from django.core.urlresolvers import reverse

# Create your views here.
# def index(request):
    # response = "Hello, I am your third request!"
    # print("This is views.py in app3")
    # return HttpResponse(response)


# accessed by clicking All Users link on home page (app1)
# gets all user objects from database, id of user in session
# renders to all_users.html to display all users, link to edit_profile for session user:
def all_users(request):
    print("This is the all_users method in app3 views.py")
    if 'user_id' not in request.session:
        return redirect('loginreg:index')
# saving users group in context
    else:
        context = {
            'users': User.objects.all(),
            'user_id': request.session['user_id']
        }
        return render(request, 'app3_messages/all_users.html', context)


# accessed by clicking edit-your-profile link on All Users page
# gets session user's object from database and renders page by id
# renders to edit_profile.html, displays form for editing user name/email
def edit_profile(request, id):
    print("This is the edit_profile method in app3 views.py")
    user = User.objects.get(id=request.session['user_id'])
    print("NOT POST")
    print("User is: #", user.id, user.first_name, user.last_name)
    context = {
        'user': User.objects.get(id=request.session['user_id']),
    }
    return render(request, 'app3_messages/edit_profile.html', context)


# route for form data in Edit Info box on edit_profile.html
# allows users to change their name and email
# accessed by Save button, edited data changed in database
def edit_info(request, id):
    print
    ("This is the edit_info method in app3 views.py")

# checking id
    print("User ID is:", id)

# when the form to edit user name and email is submitted:
    if request.method == "POST":
        print("POST")

# updates session user's object in database and returns to all_users page
        edit_user = User.objects.get(id=id)
        print("User is: #", edit_user.id, edit_user.email, edit_user.first_name, edit_user.last_name)
        edit_user.email = request.POST['email']
        edit_user.first_name = request.POST['first_name']
        edit_user.last_name = request.POST['last_name']
        edit_user.save()
        print("Edited user:", edit_user.email, edit_user.first_name, edit_user.last_name)

# needs check for duplicate email

# ALWAYS REDIRECT after a post request
# the updated user data will appear on the all_users page
        return redirect('messages:all_users')
# will redirect to the same page even if the data isn't updated
    else:
        return redirect('messages:all_users')


# route for form data in Change Password box on edit_profile.html
# allows users to change their password
# accessed by Update Password button, edited data changed in database
def change_pw(request, id):
    if request.method == 'POST':
        edit_user = User.objects.get(id=id)
        print("Editing user:", edit_user.first_name, edit_user.last_name)
        edit_user.password = request.POST['password']
        edit_user.pw_confirm = request.POST['pw_confirm']

# needs password = pwconfirm validation

        #hashes the updated password with bcrypt
        edit_user.password = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
        edit_user.save()

# ALWAYS REDIRECT after a post request
        return redirect('messages:all_users')
# will redirect to the same page even if the data isn't updated
    else:
        return redirect('messages:all_users')


# TO COME: route for form data in Edit Description box on edit_profile.html
def edit_desc(request, id):
    print("This is edit_desc method in app3 views.py")
    return redirect('messages:all_users')
    # return redirect('messages:user_posts')


# ***** POSTS NOT WORKING YET *****
# ***** Refer to The_Wall for posting functionality *****
# accessed by name-links on both All Users and Manage Users pages
# renders to profile.html, which displays users' profile data by id
# all users can access profile pages and add posts
def profile(request, id):
    print("This is the profile method in app3 views.py")

    # context = {
    # user_post object is all posts sent to a user (10)
        # 'posts_to_user': User_posts.objects.all(id=id)
    # }


# saving individual user in context to display at top of profile page
    context = {
    # User object is for user name clicked on
        'user': User.objects.get(id=id),
    # User_posts object is all posts sent to the above user
        # 'posts_to_user': User_posts.objects.all(id=user_posts.id)
    }

    print("Profile page, user id is:", id)
    return render(request, 'app3_messages/profile.html', context)


# route for users' posts
def user_posts(request, id):
    print("This is the user_posts method in app3 views.py")

# creates new post object
# returns all post objects for display on profile page
    if request.method == 'POST':
        print("POST", id)
        newpost = User_posts.objects.create(post=request.POST['message'])
        print("New post is:", newpost)
        return redirect('messages:profile')
    return redirect('messages:profile')

apps/app3_messages/templates/app3_messages/all_users.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app3_messages/css/style.css' %}" media="screen" title="no title">
    <title>All Users</title>
  </head>
  <body>

    <div class="tablewrap">
      <h1>All Users</h1>

      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>email</th>
            <th>created at</th>
            <th>user_level</th>
            </tr>
        </thead>


        {% for user in users %}
          <tr>
            <td>{{ user.id }}</td>
            <td><a href="{% url 'messages:profile' id=user.id %}"> {{ user.first_name }} {{ user.last_name }}</a></td>
            <td>{{ user.email }} </td>
            <td>{{ user.created_at }}</td>
            <td>{{ user.level }}</td>

          </tr>
        {% endfor %}

      </table>


      <div class="editprofile">

        <p><a href="{% url 'loginreg:index' %}">Home</a></p>

<!-- Link to Edit profile page -->
        <p><a href="{% url 'messages:edit_profile' id=user_id %}"> {{ request.session.user.first_name }} Would you like to edit your profile?</a></p>

<!-- Link to Manage Users page -->
        <p><a href="{% url 'admins:index' %}">Manage Users (Administrators only)</a></p>

      </div>


    </div> <!-- tablewrap end div -->
  </body>
</html>

apps/app3_messages/templates/app3_messages/edit_profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app3_messages/css/style.css' %}" media="screen" title="no title">

    <title>Edit Profile page</title>
  </head>
  <body>

    <h1>Edit profile for {{ user.first_name }} {{ user.last_name }}</h1>
    <div class="wrapper">
      <div class="editbox">

        <!-- Users can update their email address and name -->
        <form action="{% url 'messages:edit_info' id=user.id %}" method="POST" id="edit_email">
          {% csrf_token %}

          <h2>Edit Information</h2>

          <h4>Email Address:</h4>
          <input type="text" name="email">
          <h4>First Name:</h4>
          <input type="text" name="first_name">
          <h4>Last Name:</h4>
          <input type="text" name="last_name">
          <button type="submit" form="edit_email" value="">Save</button>
        </form>

      </div> <!-- edit box end div -->


<!-- Users can update their password -->
      <div class="editbox">

        <form action="{% url 'messages:change_pw' id=user.id %}" method="POST" id="edit_pw">
          {% csrf_token %}

          <h2>Change Password</h2>

          <h4>Password:</h4>
          <input type="password" name="password">
          <h4>Password Confirmation:</h4>
          <input type="password" name="pw_confirm">
          <button type="submit" form="edit_pw" value="">Update Password</button>

      </div>


<!-- The textarea data isn't submitting; don't know why -->
<!-- Users can add a description  -->
      <div class="footer">
        <form action="{% url 'messages:edit_desc' id=user.id %}" method="POST" id="add_desc">
          {% csrf_token %}

          <h2>Edit Description</h2>
          <textarea name = "message" rows="3" cols="75"></textarea>
          <!-- <input type="textarea" name = "message" rows="3" cols="75"></textarea> -->
          <button type="submit" form="add_desc" value="">Save</button>
        </form>
      </div>

    </body>
  </html>

apps/app3_messages/templates/app3_messages/hold.html
def user_posts(request, id):
    print("This is the profile method in app3 views.py")
    messages_list = list()
    if request.method == 'POST':
        request.session['messages_list'].append(messageslist)
        # print(post_data['message'])
    print("Profile method, user is:", id)
    return redirect('messages:profile')


# Not working yet
# only logged-in users can make updates to their profile page
def user_update(request):
    if 'user_id' not in request.session:
        print("User not in session")
        return redirect('loginreg:index')
    else:
        print("User in session")
        return render(request, 'app3_messages/profile.html')

==================

        <form action = "{% url 'messages:user_posts' id=user.id %}" method="POST">
          {% csrf_token %}
          <textarea name = "message" rows="3" cols="45"></textarea>
          <button type="Submit" value="Post">Post</button>
        </form>

  <!-- no routing start -->
        <div class = "messages">
       <!-- This loop is posted messages -->
       {% for posts in request.session.messages_list %}
        <p> {{ response_to_views }}</p>
       {% endfor %}
        </div>

  <!-- no routing end -->
    </div><!-- miniwrap end div -->
  </body>
  </html>



  def edit_desc(request, id):
      print("This is edit_desc method in app3 views.py")
      if request.method == 'POST':
          # edit_desc = User_profile.objects.get(id=id)
      return render(request, 'app3_messages/profile.html', context)



      # Not working yet, may not be needed
      # only logged-in users can make updates to their profile page
      def user_update(request):
          if 'user_id' not in request.session:
              print("User not in session")
              return redirect('loginreg:index')
          else:
              print("User in session")
              return redirect('messages:user_posts')

apps/app3_messages/templates/app3_messages/profile.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app3_messages/css/style.css' %}" media="screen" title="no title">
    <title>Profile</title>
  </head>
  <body>

<!-- displays user info on profile page -->
    <div class="miniwrap">
      <h1>{{ user.first_name }} {{ user.last_name }}
        <h3>Registered at: {{ user.created_at }}</h3>
        <h3>User ID: #{{ user.id }}</h3>
        <h3>Email address:{{ user.email }}</h3>

<!-- no input for description yet -->
        <h3>Description: {{ description }}</h3>
        <br>

<!-- section where users post messages -->
        <h2>Leave a message for {{ user.first_name }}</h2>
<!-- form routes to app3 profile method, which redirects to user_posts method -->
        <form action = "{% url 'messages:user_posts' id=user.id %}" method="POST">
          {% csrf_token %}
          <textarea name = "message" rows="4" cols="70"></textarea>
          <button type="Submit" value="Post">Post</button>
        </form>

  <!-- no routing start -->
        <div class = "messages">
       <!-- This loop is posted messages -->
       {% for posts in request.session.messages_list %}
        <p> {{ response_to_views }}</p>
       {% endfor %}
        </div>

<!-- no routing end -->
    </div><!-- miniwrap end div -->
  </body>
</html>

<!-- NOTES -->
<!-- Description: (displays text entered by user) -->
<!-- Leave a message for first_name (textarea field below with green Post button below that) -->

<!-- Under this will be displayed any posted messages in textarea fields, with header: -->
<!-- Name wrote (on left), _ hours ago (on right) -->

<!-- There should also be functionality to leave posts on the posts; not sure how to do this -->