apps/app2_manage_users/urls.py
#app-level url code:
from django.conf.urls import url, include
from . import views

# APP2
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_user$', views.add_user, name='add_user'),
    url(r'^edit_user/(?P<id>\d+)$', views.edit_user, name='edit_user'),
    url(r'^edit_password/(?P<id>\d+)$', views.edit_password, name='edit_password'),
    url(r'^remove_user_check/(?P<id>\d+)$', views.deletecheck, name='check'),
    # url(r'^remove_user$', views.remove_user, name='remove')
    url(r'^remove_user/(?P<id>\d+)$', views.remove_user, name='remove_user')
]

apps/app3_messages/urls.py
#app-level url code:
from django.conf.urls import url, include
from . import views

# app3_messages
urlpatterns = [
# route for rendering all_users.html:
    url(r'^$', views.all_users, name='all_users'),

# route for rendering edit_profile.html:
    url(r'^edit_profile/(?P<id>\d+)$', views.edit_profile, name='edit_profile'),

# route for sending form data in edit info box on edit_profile.html:
    url(r'^edit_info/(?P<id>\d+)$', views.edit_info, name='edit_info'),

# route for sending form data in change password box on edit_profile.html:
    url(r'^change_pw/(?P<id>\d+)$', views.change_pw, name='change_pw'),

# route for sending form data in edit description box on edit_profile.html:
    url(r'^edit_desc/(?P<id>\d+)$', views.edit_desc, name='edit_desc'),


    url(r'^profile/(?P<id>\d+)$', views.profile, name='profile'),


    url(r'^user_posts/(?P<id>\d+)$', views.user_posts, name='user_posts'),

    # url(r'^user_update$', views.user_update, name='user_update'),
    # url(r'^display_messages/(?P<id>\d+)$', views.display_messages, name='display'),
]

user_dashboard2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.app1_login_register.urls', namespace="loginreg")),
    url(r'^admins/', include('apps.app2_manage_users.urls', namespace='admins')),
    url(r'^messages/', include('apps.app3_messages.urls', namespace='messages')),
]

apps/app2_manage_users/models.py
from django.db import models
from apps.app1_login_register.models import User

# Create your models here.

apps/app2_manage_users/views.py
from django.shortcuts import render, HttpResponse, redirect
from apps.app1_login_register.models import User
from django.contrib import messages
import re, bcrypt

# displays user group on manage_users.html
# accessed by clicking Administrators link on home page
def index(request):
    print("This is the index method in app2 views.py")

# If not logged in, users will be returned to the home page
    if 'user_level' not in request.session:
        return redirect('loginreg:index')
# Only level 9 users can access manage_users.html
    elif request.session['user_level'] == 9:
        print("User is an administrator")

    # saving users group in context
        context = {
            'users': User.objects.all()
        }

        all_users=User.objects.all()
        print("All users are:", all_users)
        return render(request, 'app2_manage_users/manage_users.html', context)
# Logged-in users who are not a level 9 will be returned to the home page
    else:
        print("User is not an administrator. User level is:", request.session['user_level'])
        return redirect('loginreg:index')


# displays add_user.html; admins can add a new user
def add_user(request):
    print("This is the add_users method in app2 views.py")
    if request.method == 'POST':
        response_from_models = User.objects.validate_user(request.POST)
        print("Response from models:", response_from_models)
        return redirect('admins:index')
    return render(request, 'app2_manage_users/add_user.html')


# Administrators can edit individual users by clicking Edit link on manage_users.html
def edit_user(request, id):
    print("This is the edit_users method in app2 views.py")

# gets user object to be edited
    context = {
        'user': User.objects.get(id=id)
    }
    print("edit_user method, user is:", id)

# updates user object with data from form
    if request.method == 'POST':
        edit_user = User.objects.get(id=id)
        print("Editing user:", edit_user.first_name, edit_user.last_name)

        edit_user.email = request.POST['email']


        # needs check for duplicate email


        # saves form data in database:
        edit_user.first_name = request.POST['first_name']
        edit_user.last_name = request.POST['last_name']
        edit_user.level = request.POST['level']
        edit_user.save()

# returns all user objects, including the edited object, to the page for display
        context = {
            'users': User.objects.all()
        }
        return render(request, 'app2_manage_users/manage_users.html', context)
# displays page before editing
    return render(request, 'app2_manage_users/edit_user.html', context)


# Admins can update password
def edit_password(request, id):
    if request.method == 'POST':
        edit_user = User.objects.get(id=id)
        print("Editing user:", edit_user.first_name, edit_user.last_name)
        edit_user.password = request.POST['password']
        edit_user.pw_confirm = request.POST['pw_confirm']

# password = pwconfirm validation; aborts if passwords don't match
        if not edit_user.password == edit_user.pw_confirm:
            redirect('admins:index')
        else:
            #hashes the updated password with bcrypt
            edit_user.password = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())
            edit_user.save()

    # returns all user objects, including the edited object, to the page for display
            context = {
                'users': User.objects.all()
            }
            return render(request, 'app2_manage_users/manage_users.html', context)
    else:
        context = {
            'user': User.objects.get(id=id)
        }
        return render(request, 'app2_manage_users/edit_user.html', context)


# asks Administrators whether they want to delete a user object
def deletecheck(request, id):
    print("This is deletecheck function in views.py")
    context = {
        'user': User.objects.get(id=id)
    }
    return render(request, 'app2_manage_users/delete_user.html', context)


#deletes a user from the database
def remove_user(request, id):
    print("This is the remove_user method in app3 views.py")
    User.objects.get(id=id).delete()
    context = {
        'users': User.objects.all()
    }
    return render(request, 'app2_manage_users/manage_users.html', context)

apps/app2_manage_users/templates/app2_manage_users/add_user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit User</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'app2_manage_users/css/style.css' %}" media="screen" title="no title">
  </head>
  <body>

    <div class="wrapper">

      <div class="header">
        <form action="{% url 'admins:index' %}" method="POST" id="dashboard">
          {% csrf_token %}

          <!-- Heading text and return button display on the same line using inline format  -->
          <h1 class="ele_line">Add a new user</h1>
          <button class="ele_inline" type="submit" form="dashboard" value="">Return to Dashboard</button>
        </form>
      </div>

      <div class="editbox">

<!-- Admins can update email address, user name and user level -->
        <form action = "{% url 'admins:add_user' %}" method="POST" id="adduser">
          {% csrf_token %}

            <h4>Email Address:</h4>
            <input type="text" name="email">
            <h4>First Name:</h4>
            <input type="text" name="first_name">
            <h4>Last Name:</h4>
            <input type="text" name="last_name">
            <h4>Password:</h4>
            <input type="password" name="password">
            <h4>Password Confirmation:</h4>
            <input type="password" name="confirmPW">

            <button type="submit" form="adduser" value="">Save</button>
          </form>
        </div>

    </div><!-- wrapper end div -->

  </body>
</html>

apps/app2_manage_users/templates/app2_manage_users/delete_user.html
<!DOCTYPE html>
<html lang = "en">
  <head>

    <!-- <meta charset="utf-8"> -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Delete page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'app2_manage_users/css/style.css' %}" media="screen" title="no title">
  </head>

  <body>

    <div class="miniwrap">
      <h2>Are you sure you want to delete this user?</h2>
      <h4>Name: {{ user.first_name }} {{ user.last_name }}</h4>
      <h4>ID: {{ user.id }}</h4>

<!-- No button routes back to index page -->
<!-- Yes button routes to remove function in views.py -->
      <!-- <a href='/'><button type="buttonB">No</button></a> -->
      <!-- <a href='/remove/{{ course.id }}'><button type="buttonC">Yes! I want to delete this</button></a> -->

<!-- Note: It's illegal to wrap a button in an anchor tag (above), as it doesn't work in all browsers -->
<!-- So these are anchor tags that have been styled as buttons in css -->
    <div class="buttonrow">
      <p><a href = '{% url 'admins:index' %}' class="buttonB">No, I don't want to delete this user</a></p>
      <p><a href = '{% url 'admins:remove_user' id=user.id %}' class="buttonC">Yes! I want to delete this user</a></p>
    </div>
<!-- Routes back to manage_users.html, regardless of whether a user is deleted -->


    </div>
  </body>
</html>

apps/app2_manage_users/templates/app2_manage_users/edit_user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit User</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'app2_manage_users/css/style.css' %}" media="screen" title="no title">
  </head>
  <body>

    <div class="wrapper">

      <div class="header">
        <form action="{% url 'admins:index' %}" method="POST" id="dashboard">
          {% csrf_token %}

          <!-- Heading text and return button display on the same line using inline format  -->
          <h1 class="ele_line">Edit user {{ user.id }}</h1>
          <button class="ele_inline" type="submit" form="dashboard" value="">Return to Dashboard</button>
        </form>
      </div>

      <div class="editbox">

<!-- Admins can update email address, user name and user level -->
        <form action = "{% url 'admins:edit_user' id=user.id %}" method="POST" id="edituser">
          {% csrf_token %}

            <h2>Edit Information</h2>

            <h4>Email Address:</h4>
            <input type="text" name="email">
            <h4>First Name:</h4>
            <input type="text" name="first_name">
            <h4>Last Name:</h4>
            <input type="text" name="last_name">

          <!-- request.Post['user_level'] in views.py-->
            <h4>User Level:</h4>
            <select name="level">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
            </select></td>
            <button type="submit" form="edituser" value="">Save</button>
          </form>
        </div> <!-- edit box end div -->


<!-- Admins can update user password -->
        <div class="editbox">
          <form action = "{% url 'admins:edit_password' id=user.id %}" method="POST" id="change_pw">
            {% csrf_token %}

            <h2>Change Password</h2>

            <h4>Password:</h4>
            <input type="password" name="password">
            <h4>Password Confirmation:</h4>
            <input type="password" name="pw_confirm">
            <button type="submit" form="change_pw" value="">Update Password</button>
          </form>
        </div>

    </div><!-- wrapper end div -->

  </body>
</html>

apps/app2_manage_users/templates/app2_manage_users/manage_users.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app2_manage_users/css/style.css' %}" media="screen" title="no title">
    <title>Manage Users</title>
  </head>
  <body>
    <!-- <h1>This is manage_users.html in app2</h1> -->

      <!-- <h1>Manage Users</h1> -->

<!-- page header and anchor link styled like a button, aligned horizontally -->
    <div class="header">
      <p><h1 class="one_line">Manage Users</h1><a href="{% url 'admins:add_user' %}">Add New</a></p>
    </div>

<!-- coding for a page header and an actual form button, aligned horizontally -->
    <!-- <div class="header"> -->
      <!-- <form action="{% url 'admins:add_user' %}" method="POST" id="addnew"> -->
        <!-- {% csrf_token %} -->

        <!-- <h1 class="one_line">Manage Users</h1> -->
        <!-- <button class="one_inline" type="submit" form="addnew" value="">Add New</button> -->
      <!-- </form> -->
    <!-- </div> -->


    <div class="tablewrap">
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>email</th>
            <th>created at</th>
            <th>user_level</th>
            <th>actions</th>
          </tr>
        </thead>


        {% for user in users %}
          <tr>
            <td>{{ user.id }}</td>
            <td><a href="{% url 'messages:profile' id=user.id %}"> {{ user.first_name }} {{ user.last_name }}</a></td>
            <td>{{ user.email }} </td>
            <td>{{ user.created_at }}</td>
            <td>{{ user.level }}</td>


<!-- Routes admins to functions for editing and deleting users -->
            <td><a href="{% url 'admins:edit_user' id=user.id %}">Edit</a> <a href="{% url 'admins:check' id=user.id %}">Remove</a></td>

          </tr>
        {% endfor %}

      </table>
    </div>

    <!-- page header and anchor link styled like a button, aligned horizontally -->
    <div class="footer">
      <p><a href="{% url 'loginreg:index' %}">Home</a></p>
    </div>
  </body>
</html>