apps/app1_login_register/urls.py
#app-level url code:
from django.conf.urls import url, include
from . import views

# app1
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^login$', views.login, name="login"),
    url(r'^register$', views.register, name="register"),
    url(r'^logout$', views.logout, name="logout"),

]

apps/app3_messages/urls.py
#app-level url code:
from django.conf.urls import url, include
from . import views

# app3_messages
urlpatterns = [
# route for rendering all_users.html:
    url(r'^$', views.all_users, name='all_users'),

# route for rendering edit_profile.html:
    url(r'^edit_profile/(?P<id>\d+)$', views.edit_profile, name='edit_profile'),

# route for sending form data in edit info box on edit_profile.html:
    url(r'^edit_info/(?P<id>\d+)$', views.edit_info, name='edit_info'),

# route for sending form data in change password box on edit_profile.html:
    url(r'^change_pw/(?P<id>\d+)$', views.change_pw, name='change_pw'),

# route for sending form data in edit description box on edit_profile.html:
    url(r'^edit_desc/(?P<id>\d+)$', views.edit_desc, name='edit_desc'),


    url(r'^profile/(?P<id>\d+)$', views.profile, name='profile'),


    url(r'^user_posts/(?P<id>\d+)$', views.user_posts, name='user_posts'),

    # url(r'^user_update$', views.user_update, name='user_update'),
    # url(r'^display_messages/(?P<id>\d+)$', views.display_messages, name='display'),
]

user_dashboard2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.app1_login_register.urls', namespace="loginreg")),
    url(r'^admins/', include('apps.app2_manage_users.urls', namespace='admins')),
    url(r'^messages/', include('apps.app3_messages.urls', namespace='messages')),
]

apps/app1_login_register/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime, date
import re, bcrypt
import random

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def validate_user(self, post_data):
        print("This is UserManager in models.py", post_data)
        response_to_views = {}
        errors = []
        print("In model method:", post_data)

#first name validations:
        if not post_data['first_name']:
            errors.append('First name is required')
            print("Errors:", errors)
        if not len(post_data['first_name']) >= 2:
            errors.append('First name must be at least 2 characters')
        if not post_data['first_name'].isalpha():
            errors.append('First name must contains only letters')

#last name validations:
        if not post_data['last_name']:
            errors.append('Last name is required')
        if not len(post_data['last_name']) >= 2:
            errors.append('Last name must be at least 2 characters')
        if not post_data['last_name'].isalpha():
            errors.append('Last name must contains only letters')

#email validations:
        # sends post_data into regex to be checked for match
        if not EMAIL_REGEX.match(post_data['email']):
            errors.append('Enter a valid email')

#Password validations:
        if len(post_data['password']) < 8:
            errors.append('Password must be at least 8 characters')
        if not post_data['password'] == post_data['confirmPW']:
            errors.append('Passwords must match')

# check that submitted email is unique (non-duplicate) before other validations, because users log in with their emails
# filter will return false if list is empty, true if not empty
        if self.filter(email = post_data['email']):
            errors.append('Email is already in use')

#fail/pass validations:
        if errors:#failed validations
            response_to_views['status'] = False
            response_to_views['errors'] = errors
            print("Errors:", errors)

        else:#passed validations
            response_to_views['status'] = True

            #create a user level
            user_level = random.randint(0,9)
            print("User level is:", user_level)

            #hash the password with bcrypt
            hashed_password = bcrypt.hashpw(post_data['password'].encode(), bcrypt.gensalt())

            #create a new user object
            user = self.create(first_name = post_data['first_name'], last_name = post_data['last_name'], email = post_data['email'], password = hashed_password, level = user_level)

            print("User is:", user)
            response_to_views['user'] = user
        return response_to_views

# finding a user in the database with the user's email:
    def login_user(self, post_data):
        print("This is login_user method in models.py")
        #will be true if email found, false if it isn't:
        response_to_views = {}
        #filter will return only 1 object & won't generate error if email doesn't exist
        user = self.filter(email = post_data['email'])
        print("User:", user)
        if user:#if user email is in the database:
            # checks whether submitted password matches one in the database
            # submitted pw is hashed with same formula as db password
            # because filter returns only 1 object at a time, the user is always user[0]
            # bcrypt.checkpw returns a boolean, true or false
            if bcrypt.checkpw(post_data['password'].encode(), user[0].password.encode()):#if boolean is true:
            # user object is saved in response_to_views
                response_to_views['status'] = True
                response_to_views['user'] = user[0]#will be returned & saved in session

            else:#if password is invalid
                response_to_views['status'] = False
                response_to_views['errors'] = "Invalid email/password combination"

        else:#if user email is not found in database:
            response_to_views['status'] = False
            response_to_views['errors'] = "Invalid email"

#return response data
        return response_to_views


# Create your models here.
class User(models.Model):
    first_name=models.CharField(max_length=45)
    last_name=models.CharField(max_length=45)
    email=models.CharField(max_length=100)
    password=models.CharField(max_length=25)
    level = models.IntegerField()
    # level=models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/app1_login_register/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import User
from django.contrib import messages

# Create your views here.
def index(request):
    print("This is the index method in app1 views.py")
    return render(request, 'app1_login_register/index.html')


def register(request):
    print("This is the register method in app1 views.py")
    if request.method == 'POST':
        print("This is the POST register method in app1 views.py")
        print("Request.POST:", request.POST)
        response_from_models = User.objects.validate_user(request.POST)
        print("Response from models:", response_from_models)
        if response_from_models['status']:#if true
            # passed the validations and created a new user

            # user data can now be saved in session, by id:
            request.session['user_id'] = response_from_models['user'].id
            request.session['user_first_name'] = response_from_models['user'].first_name
            request.session['user_level'] = response_from_models['user'].level
            print(request.session['user_id'], request.session['user_first_name'], request.session['user_level'])

            # return redirect('loginreg:success')
            # return redirect('admins:index')#goes to index method in app2
            return redirect('messages:all_users')#goes to all_users method in app3

        else:#validation not passed
            for error in response_from_models['errors']:
                messages.error(request, error)
            return redirect('loginreg:register')
    return render(request, 'app1_login_register/register.html')


#linked from anchor tag on index.html; takes user to login.html
def login(request):
    print("This is the login method in app1 views.py")
    if request.method == 'POST':
        print("This is the POST login method in app1 views.py")
        print("Request.POST:", request.POST)
        response_from_models = User.objects.login_user(request.POST)
        print("Response from models:", response_from_models)
        if response_from_models['status']:#if true (validations are met):

            #saves user data in session, sends user to success page:
            request.session['user_id'] = response_from_models['user'].id
            request.session['user_first_name'] = response_from_models['user'].first_name
            request.session['user_level'] = response_from_models['user'].level
            print("Session is:", request.session['user_id'], request.session['user_level'])

            # return redirect('loginreg:success')
            # return redirect('admins:index')
            return redirect('messages:all_users')
            # return redirect('messages:index')#goes to all_users method in app3


        else:#validation not passed
            # no for-loop here; only 1 message will appear at a time
            # errors: either invalid email or invalid email/pw combo
            messages.error(request, response_from_models['errors'])
            return redirect('loginreg:login')
    else:
        return render(request, 'app1_login_register/login.html')

def logout (request):
    print("This is the logout method in app1 views.py")
    if request.method == 'POST':
        request.session.clear()#deletes everything in session
    return redirect('loginreg:index')

apps/app1_login_register/templates/app1_login_register/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app1_login_register/css/style.css' %}" media="screen" title="no title">
    <title>App 1 index page</title>
  </head>
  <body>
    <div class="wrapper">

      <div class="header">
        <h1>Welcome to the User's Dashboard!</h1>
      </div>

      <div class="centerwrap">

        <div class="nav">
          <h2>This is the navigation bar</h2>
          <p><a href="{% url 'loginreg:login' %}">Log in</a></p>
          <p><a href="{% url 'loginreg:register' %}">Register</a></p>

          <!-- links to manage_users.html in App 2 -->
          <p><a href="{% url 'admins:index' %}">Administrators</a></p>
          <!-- links to all_users.html in App 3 -->
          <p><a href="{% url 'messages:all_users' %}">All Users</a></p>

          <p><a href="{% url 'loginreg:logout' %}">Log out</a></p>
<!-- Needs a goodbye message -->

        </div>

        <div class="main">
          <h2>This is the main bar</h2>
          <h4>Here are paragraphs of information on what this website is about.</h4>
          <h4>Here are paragraphs of information on what this website is about.</h4>
        </div>

      </div><!--centerwrap end div-->

      <div class="footer">
        <h3>This is the footer</h3>
      </div>

    </div><!-- wrapper end div -->
  </body>
</html>

apps/app1_login_register/templates/app1_login_register/login.html
<!DOCTYPE html>
<html>
  <head>
    <!-- <meta charset="utf-8"> -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'app1_login_register/css/style.css' %}" media="screen" title="no title">
    <title>App 1 Login page</title>
  </head>
  <body>

    <div class="wrapper">

        <!-- loginreg is the named route for app1 in main-level urls.py -->
        <!-- register is a named route in apps-level urls.py -->

        <form class="" action="{% url 'loginreg:login' %}" method="POST">
          {% csrf_token %}

          <h1>Log in</h1>
          <h3>Email: <input type="text" name="email" value=""></h3>
          <h3>Password: <input type="password" name="password" value=""></h3>
          <input type="Submit" value="Login">
          <br>
          <br>
          <p><a href="{% url 'loginreg:register' %}">Don't have an account? Register</a></p>
        </form>

      <!-- displaying error messages -->
      <div class="messages">
        {% if messages %}
          <!-- <ul class="messages"> -->
            <!-- {% for message in messages %} -->
              <li><span class="errMessage">{{ message }}</span></li>
            <!-- {% endfor %} -->
          <!-- </ul> -->
        {% endif %}
      </div>

    </div><!-- wrapper end div -->

  </body>
</html>

apps/app1_login_register/templates/app1_login_register/register.html
<!DOCTYPE html>
<html>
  <head>
    <!-- <meta charset="utf-8"> -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'app1_login_register/css/style.css' %}" media="screen" title="no title"  charset="utf-8">
    <title>App 1 Registration pag3e</title>
  </head>
  <body>

    <div class="wrapper">
        <div class="registration">

            <!-- loginreg is the named route for app1 in main-level urls.py -->
            <!-- register is a named route in apps-level urls.py -->
            <form class="" action="{% url 'loginreg:register' %}" method="POST">
              {% csrf_token %}

              <h1>Registration</h1>
              <h3>Email: <input type="text" name="email" value=""></h3>

              <h3>First Name: <input type="text" name="first_name" value=""></h3>
              <h3>Last Name: <input type="text" name="last_name" value=""></h3>

              <!-- type="password" hides the password -->
              <h3>Password: <input type="password" name="password" value=""></h3>
              <h3>Confirm Password: <input type="password" name="confirmPW" value=""></h3>

              <input type="Submit" value="Register">
              <br>
              <br>
              <p><a href="{% url 'loginreg:login' %}">Already have an account? Log in</a></p>
            </form>

        </div><!-- end of registration -->

        <!-- displaying error messages -->
          {% if messages %}
            <ul class="messages">
              {% for message in messages %}
                <li><span class="errMessage">{{ message }}</span></li>
              {% endfor %}
            </ul>
          {% endif %}

      </div><!--wrapper end div-->
  </body>
</html>